GET /v1/items/1
Content-Type: application/json
Host: localhost:8080

###

GET /v2/items/1
Content-Type: application/json
Host: localhost:8080

###

GET /items?page=0&size=5
Content-Type: application/json
Host: localhost:8080

###

GET /items?page=1&size=5
Content-Type: application/json
Host: localhost:8080
